version: "3.7"

services:
  dbas:
    image: dbas_web
    ports:
      - "4284:4284"
    depends_on:
      - db
    environment:
      AUTHN_SECRET: "secret"
      DB_PW: "bla"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "postgres"
      KEY_PATH: devkey.pem
      PUBKEY_PATH: devpublic.pem
      URL: "http://0.0.0.0:4284"

  db:
    image: dbas_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "bla"

  decidotron:
    image: decidotron
    ports:
      - "5005:8080"
    depends_on:
      - db
    volumes:
      - ./decidotron_store:/store
      - ./sample-conf.edn:/config/production.edn:ro